package com.rodrigmatrix.rastreio.presentation.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006e21)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF69ff83)
val md_theme_light_onPrimaryContainer = Color(0xFF002106)
val md_theme_light_secondary = Color(0xFF51634f)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd4e8cf)
val md_theme_light_onSecondaryContainer = Color(0xFF101f10)
val md_theme_light_tertiary = Color(0xFF006874)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF8ef1ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001f24)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfdf6)
val md_theme_light_onBackground = Color(0xFF1a1c18)
val md_theme_light_surface = Color(0xFFfdfdf6)
val md_theme_light_onSurface = Color(0xFF1a1c18)
val md_theme_light_surfaceVariant = Color(0xFFdee4d9)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_outline = Color(0xFF72796f)
val md_theme_light_inverseOnSurface = Color(0xFFf1f1ea)
val md_theme_light_inverseSurface = Color(0xFF2f312c)

val md_theme_dark_primary = Color(0xFF00e551)
val md_theme_dark_onPrimary = Color(0xFF00390c)
val md_theme_dark_primaryContainer = Color(0xFF005316)
val md_theme_dark_onPrimaryContainer = Color(0xFF69ff83)
val md_theme_dark_secondary = Color(0xFFb9ccb4)
val md_theme_dark_onSecondary = Color(0xFF253424)
val md_theme_dark_secondaryContainer = Color(0xFF3a4b39)
val md_theme_dark_onSecondaryContainer = Color(0xFFd4e8cf)
val md_theme_dark_tertiary = Color(0xFF4fd8eb)
val md_theme_dark_onTertiary = Color(0xFF00363d)
val md_theme_dark_tertiaryContainer = Color(0xFF004f59)
val md_theme_dark_onTertiaryContainer = Color(0xFF8ef1ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c18)
val md_theme_dark_onBackground = Color(0xFFe3e3dc)
val md_theme_dark_surface = Color(0xFF1a1c18)
val md_theme_dark_onSurface = Color(0xFFe3e3dc)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c9bd)
val md_theme_dark_outline = Color(0xFF8c9388)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c18)
val md_theme_dark_inverseSurface = Color(0xFFe3e3dc)

val seed = Color(0xFF12f35d)
val error = Color(0xFFba1b1b)