package com.rodrigmatrix.packagetracker.presentation.theme

import androidx.compose.ui.graphics.Color

val theme_light_mailed = Color(0xFF048334)
val theme_light_alert = Color(0xFFFFD500)
val theme_light_shipped = Color(0xFF275EFF)
val theme_light_inRoute = Color(0xFFFF9800)
val theme_light_inProgress = Color(0xFF006877)
val theme_light_done = Color(0xFF048334)
val theme_light_disabled = Color(0xFF414940)


val md_theme_light_primary = Color(0xFF006e29)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF7afd92)
val md_theme_light_onPrimaryContainer = Color(0xFF002107)
val md_theme_light_secondary = Color(0xFF516351)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd4e8d1)
val md_theme_light_onSecondaryContainer = Color(0xFF0f1f11)
val md_theme_light_tertiary = Color(0xFF006877)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF9befff)
val md_theme_light_onTertiaryContainer = Color(0xFF001f25)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcf7)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfcfcf7)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFdde5d9)
val md_theme_light_onSurfaceVariant = Color(0xFF414940)
val md_theme_light_outline = Color(0xFF71796f)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1eb)
val md_theme_light_inverseSurface = Color(0xFF2e312d)

val md_theme_dark_primary = Color(0xFF5bdf78)
val md_theme_dark_onPrimary = Color(0xFF003911)
val md_theme_dark_primaryContainer = Color(0xFF00531d)
val md_theme_dark_onPrimaryContainer = Color(0xFF7afd92)
val md_theme_dark_secondary = Color(0xFFb8ccb5)
val md_theme_dark_onSecondary = Color(0xFF243425)
val md_theme_dark_secondaryContainer = Color(0xFF3a4b3a)
val md_theme_dark_onSecondaryContainer = Color(0xFFd4e8d1)
val md_theme_dark_tertiary = Color(0xFF50d7ef)
val md_theme_dark_onTertiary = Color(0xFF00363f)
val md_theme_dark_tertiaryContainer = Color(0xFF004e5a)
val md_theme_dark_onTertiaryContainer = Color(0xFF9befff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe1e3dd)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe1e3dd)
val md_theme_dark_surfaceVariant = Color(0xFF414940)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c9be)
val md_theme_dark_outline = Color(0xFF8b9389)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe1e3dd)

val seed = Color(0xFF44ca66)
val error = Color(0xFFba1b1b)